export { default as Navbar } from './navbar/Navbar';
export { default as Home } from './home/Home';
export { default as About } from './about/About';
export { default as Dashboard } from './dashboard/Dashboard';
export { default as Login } from './login/Login';
export { default as Signup } from './signup/Signup';
export { default as AllPokemons } from './getAll/AllPokemons';
export { default as OnePokemon } from './getOne/OnePokemon';
export { default as CreatePokemon } from './createOne/CreatePokemon';
